# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(db_index=True, editable=False, max_length=30)),
                ('op_number', models.CharField(db_index=True, editable=False, max_length=30)),
                ('doctor_name', models.CharField(max_length=200)),
                ('consultation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('consultation_type', models.CharField(choices=[('NEW', 'New'), ('REVISIT', 'Revisit'), ('HOME_VISIT', 'Home Visit')], default='NEW', max_length=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, help_text='Optional travel charge for Home Visit bills. ₹0 for NEW/REVISIT.', max_digits=10)),
                ('revisit_valid_until', models.DateField(blank=True, editable=False, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time MRD registration charge. Auto-populated for first-visit bills; 0 for returning patients.', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat discount amount applied to this bill (not a percentage).', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='subtotal (registration_fee + consultation_fee) minus discount_amount. Computed on save, never below 0.', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=10)),
                ('upi_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('registration_fee_paid', models.BooleanField(default=False, help_text='True once the one-time MRD registration fee has been collected.')),
                ('branch', models.ForeignKey(blank=True, help_text='Auto-set from patient.branch on save if not provided.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_bills', to='administration.branch')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_bills', to='doctor.doctorprofile')),
                ('guest_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_bills', to='administration.guestdoctorprofile')),
            ],
            options={
                'ordering': ['-bill_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_mrd', models.BooleanField(default=True, help_text="False for a home-visit entry that hasn't been issued a real MRD yet. Prescriptions and lab history stay blocked until this is True and mrd_number is assigned.")),
                ('mrd_number', models.CharField(blank=True, db_index=True, editable=False, help_text='NULL until has_mrd is True — a home-visit-only patient may not have one yet.', max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')])),
                ('place', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('registration_fee_paid', models.BooleanField(default=False, help_text='True once the one-time MRD registration fee has been collected.')),
                ('assigned_doctor', models.ForeignKey(blank=True, help_text='The primary doctor assigned to this patient. Only this doctor (and admins) can view the patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='doctor.doctorprofile')),
                ('branch', models.ForeignKey(help_text='Branch this patient record belongs to. Re-registration at a different branch creates a new Patient row with its own MRD, not a cross-branch link.', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='administration.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPreBooking',
            fields=[
                ('prebooking_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, editable=False, max_length=30)),
                ('new_patient_name', models.CharField(blank=True, help_text='Quick name entry for a new patient not yet MRD-registered.', max_length=300, null=True)),
                ('new_patient_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')])),
                ('new_patient_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('new_patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_mode', models.CharField(choices=[('CALL', 'Call-in'), ('WALKIN', 'Walk-in'), ('WEBSITE', 'Public Website')], default='CALL', max_length=10)),
                ('consultation_type', models.CharField(choices=[('NEW', 'New'), ('REVISIT', 'Revisit'), ('HOME_VISIT', 'Home Visit')], default='NEW', max_length=10)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, help_text='Optional travel charge for Home Visit bookings. ₹0 for NEW/REVISIT.', max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time MRD registration charge, locked in when payment is collected.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI')], max_length=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='BOOKED', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text="Which branch this booking is for. Auto-set from patient.branch when an existing patient is linked; must be provided explicitly for a brand-new (not-yet-registered) patient, since there's no Patient row yet to derive it from.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prebookings', to='administration.branch')),
                ('converted_bill', models.ForeignKey(blank=True, help_text='Set once this booking has been converted into a real ConsultationBill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebooking_source', to='reception.consultationbill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebookings_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebookings', to='doctor.doctorprofile')),
                ('guest_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebookings', to='administration.guestdoctorprofile')),
                ('patient', models.ForeignKey(blank=True, help_text='Existing registered patient. NULL if this is a new, not-yet-registered patient.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prebookings', to='reception.patient')),
            ],
            options={
                'ordering': ['-requested_date', '-requested_time'],
            },
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bills', to='reception.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mrd_number'], name='reception_p_mrd_num_f4b40a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='reception_p_phone_53f142_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['place'], name='reception_p_place_004728_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['assigned_doctor'], name='reception_p_assigne_52a0a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('branch', 'mrd_number')},
        ),
        migrations.AddIndex(
            model_name='consultationprebooking',
            index=models.Index(fields=['status'], name='reception_c_status_58fb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationprebooking',
            index=models.Index(fields=['requested_date'], name='reception_c_request_f0748a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationprebooking',
            index=models.Index(fields=['payment_status'], name='reception_c_payment_9c75c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationprebooking',
            unique_together={('branch', 'reference_number')},
        ),
        migrations.AddIndex(
            model_name='consultationbill',
            index=models.Index(fields=['bill_number'], name='reception_c_bill_nu_f8371b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationbill',
            index=models.Index(fields=['op_number'], name='reception_c_op_numb_1f6d97_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationbill',
            index=models.Index(fields=['patient', 'consultation_date'], name='reception_c_patient_97556f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationbill',
            unique_together={('branch', 'bill_number'), ('branch', 'op_number', 'consultation_date')},
        ),
    ]
