# Generated by Django 5.2.16 on 2026-08-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_billingdepartment'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbill',
            name='billed_department',
            field=models.ForeignKey(blank=True, help_text="Department this consultation is billed against — may differ from the doctor's own home department.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_bills', to='administration.billingdepartment'),
        ),
    ]
