# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_equipment', to='administration.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabMaintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('ROUTINE', 'Routine'), ('REPAIR', 'Repair'), ('CALIBRATION', 'Calibration'), ('INSTALLATION', 'Installation')], max_length=20)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=15)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='lab.labequipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('REAGENT', 'Reagent'), ('CONSUMABLE', 'Consumable'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], db_index=True, default='CONSUMABLE', max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, help_text='e.g. boxes, pieces, liters', max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=25)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_id'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When this request was claimed.', null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('DELIVERED', 'Delivered')], db_index=True, default='REQUESTED', max_length=20)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_walkin', models.BooleanField(default=False, help_text='True if this is a walk-in lab request (no consultation / MRD registration)')),
                ('walkin_name', models.CharField(blank=True, help_text='Walk-in patient name (used only if is_walkin=True)', max_length=300, null=True)),
                ('walkin_phone', models.CharField(blank=True, help_text='Walk-in patient phone (optional, used only if is_walkin=True)', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')])),
                ('walkin_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Walk-in patient gender (optional)', max_length=10, null=True)),
                ('walkin_age', models.PositiveIntegerField(blank=True, help_text='Walk-in patient age (optional)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Auto-set from patient.branch on save if not provided. Required for walk-in requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='administration.branch')),
                ('claimed_by', models.ForeignKey(blank=True, help_text='Lab staff member who has claimed this request. NULL if unclaimed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_claimed', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, help_text='NULL for walk-in requests (is_walkin=True).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='doctor.consultation')),
                ('patient', models.ForeignKey(blank=True, help_text='NULL for walk-in requests (is_walkin=True).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='reception.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_id'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports_verified', to=settings.AUTH_USER_MODEL)),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lab.labrequest')),
            ],
            options={
                'ordering': ['-report_id'],
            },
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('INSURANCE', 'Insurance'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bills_created', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Auto-set from lab_request.branch on save if not provided.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_bills', to='administration.branch')),
                ('patient', models.ForeignKey(blank=True, help_text='NULL for walk-in lab bills — see lab_request.walkin_* fields instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_bills', to='reception.patient')),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='lab.labrequest')),
            ],
            options={
                'ordering': ['-bill_id'],
            },
        ),
        migrations.CreateModel(
            name='LabRequestItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.labrequest')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_value', models.TextField()),
                ('normal_range', models.TextField(blank=True, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_request_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab.labrequestitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-result_id'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code e.g. CBC, LFT, RBS', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('normal_range', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='administration.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='lab.labtest'),
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short code e.g. LFT, KFT, LIPID', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='The single price charged for the whole panel.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_groups', to='administration.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional panel this test belongs to (e.g. LFT). Leave blank for a standalone test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tests', to='lab.testgroup'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='ordered_as_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='lab.testgroup'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['status'], name='lab_labrequ_status_4409cc_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['patient', 'request_date'], name='lab_labrequ_patient_42fa5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labbill',
            unique_together={('branch', 'bill_number')},
        ),
        migrations.AlterUniqueTogether(
            name='testgroup',
            unique_together={('branch', 'code'), ('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='labtest',
            unique_together={('branch', 'code'), ('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='labrequestitem',
            unique_together={('lab_request', 'test')},
        ),
    ]
