# Generated by Django 5.2.16 on 2026-08-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auditlog_branch'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='administration.branch'),
        ),
    ]
