# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0001_initial'),
        ('manager', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(choices=[('BABY_CARE', 'Baby Care'), ('PERSONAL_CARE', 'Personal Care & Toiletries'), ('FOOD_BEVERAGE', 'Food & Beverages'), ('HOUSEHOLD', 'Household & Cleaning'), ('STATIONERY', 'Stationery & Sundries'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(blank=True, help_text="e.g. 'pack', 'piece', 'bottle'", max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_items', to='administration.branch')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralItemBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — to be paid later'), ('PAID', 'Paid in full on receipt')], max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this stock was purchased from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_item_batches', to='manager.dealer')),
                ('general_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacist.generalitem')),
            ],
            options={
                'ordering': ['general_item__name', 'expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralItemReturn',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('RECALL', 'Recall'), ('EXCESS', 'Excess / Over-ordered'), ('OTHER', 'Other')], default='OTHER', help_text='Why this stock is being returned', max_length=20)),
                ('reason_details', models.CharField(blank=True, max_length=300, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Supplier credit note / RMA number', max_length=100, null=True)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — carried forward against future orders'), ('REFUND', 'Cash refund'), ('EXCHANGE', 'Exchanged for other product(s)')], help_text='How the pharmacist expects this return to be settled by the dealer (optional).', max_length=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text="Refund owed by the dealer — quantity returned × the batch's cost price.", max_digits=12)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacist.generalitembatch')),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this return is going back to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_item_returns', to='manager.dealer')),
                ('general_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacist.generalitem')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_item_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralItemStockAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRY', 'Near Expiry / Expired')], max_length=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pharmacist.generalitembatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralItemStockLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Dispensed'), ('RETURN', 'Return'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity_changed', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='pharmacist.generalitembatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('medicine_type', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Gel'), ('LOTION', 'Lotion'), ('DROPS', 'Drops'), ('NASAL_SPRAY', 'Nasal Spray'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('POWDER', 'Powder'), ('INJECTION', 'Injection'), ('OTHER', 'Other')], default='TABLET', help_text='Dosage form, e.g. Tablet, Capsule, Syrup, Cream, Nasal Spray.', max_length=20)),
                ('strength', models.CharField(blank=True, help_text="Standard strength, e.g. '500mg', '250mg/5ml'.", max_length=100, null=True)),
                ('default_route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('NASAL', 'Nasal'), ('RECTAL', 'Rectal'), ('OTHER', 'Other')], default='ORAL', help_text='Default administration route. Auto-copied onto prescription items.', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Each branch pharmacist manages their own medicine catalogue independently.', on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='administration.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — to be paid later'), ('PAID', 'Paid in full on receipt')], help_text='How this purchase was/will be settled with the dealer (optional).', max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current physical quantity in stock')),
                ('allocated_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved/allocated to pending bills (not yet dispensed)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit (wholesale price)', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (selling price)', max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this stock was purchased from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_batches', to='manager.dealer')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacist.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReturnToProvider',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to return to provider')),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('RECALL', 'Recall'), ('OTHER', 'Other')], default='EXPIRED', help_text='Reason for returning to provider', max_length=50)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about the return reason', null=True)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — carried forward against future orders'), ('REFUND', 'Cash refund'), ('EXCHANGE', 'Exchanged for other product(s)')], help_text='How the pharmacist expects this return to be settled by the dealer (optional).', max_length=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund due from the supplier — quantity × purchase (cost) price, not MRP.', max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Return Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='REQUESTED', help_text='Current status of the return request', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the return request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the return request was last updated')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved/rejected the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_provider_returns_approved', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(help_text='Medicine batch to return to provider', on_delete=django.db.models.deletion.PROTECT, related_name='provider_returns', to='pharmacist.medicinebatch')),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this return is going back to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_returns', to='manager.dealer')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Pharmacist who requested the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_provider_returns_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicine Returns to Provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineStockLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Dispensed'), ('RETURN', 'Return'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity_changed', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='pharmacist.medicinebatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('bill_status', models.CharField(choices=[('DRAFT', 'Draft - Awaiting Review'), ('OPEN', 'Open - Items Can Be Added'), ('READY', 'Ready - Awaiting Dispensing'), ('COMPLETED', 'Completed - Items Dispensed'), ('PAID', 'Paid - Invoice Generated'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('upi_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_type', models.CharField(choices=[('MEDICINE', 'Medicine Only'), ('GENERAL', 'General Items Only'), ('PROCEDURE', 'Procedure Only'), ('MIXED', 'Mixed (2 or more of: medicine / general / procedure)')], default='MEDICINE', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Flat discount amount applied to this bill (not a percentage).', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_walkin', models.BooleanField(default=False, help_text='True if this is a walk-in patient bill (no MRD registration)')),
                ('walkin_name', models.CharField(blank=True, help_text='Walk-in patient name (used only if is_walkin=True)', max_length=300, null=True)),
                ('walkin_phone', models.CharField(blank=True, help_text='Walk-in patient phone (optional, used only if is_walkin=True)', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone must be exactly 10 digits.')])),
                ('walkin_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Walk-in patient gender (optional)', max_length=10, null=True)),
                ('walkin_age', models.PositiveIntegerField(blank=True, help_text='Walk-in patient age (optional)', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the bill was reviewed and stock was allocated', null=True)),
                ('dispensing_confirmed', models.BooleanField(default=False, help_text='Set to True when pharmacist physically confirms dispensing of items')),
                ('dispensing_confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when dispensing was physically confirmed', null=True)),
                ('sent_to_reception', models.BooleanField(default=False, help_text='True once a pharmacist has forwarded this (PAID) bill to the reception module for review/printing.')),
                ('sent_to_reception_at', models.DateTimeField(blank=True, help_text='When this bill was sent to reception.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Auto-set from patient.branch on save if not provided. Required for walk-in bills.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='administration.branch')),
                ('consultation_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='reception.consultationbill')),
                ('dispensing_confirmed_by', models.ForeignKey(blank=True, help_text='Pharmacist who physically confirmed dispensing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills_dispensing_confirmed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='reception.patient')),
                ('prescription', models.ForeignKey(blank=True, help_text='The prescription this bill was generated from. Null for walk-in bills.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='doctor.prescription')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Pharmacist who reviewed and allocated stock for this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sent_to_reception_by', models.ForeignKey(blank=True, help_text='Pharmacist who sent this bill to reception.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills_sent_to_reception', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillGeneralItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='pharmacist.generalitembatch')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_items', to='pharmacist.pharmacybill')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillMedicineItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='pharmacist.medicinebatch')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_items', to='pharmacist.pharmacybill')),
                ('prescription_item', models.ForeignKey(blank=True, help_text='Original prescription item this was dispensed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bill_items', to='doctor.prescriptionitem')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillBatchAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_quantity', models.PositiveIntegerField(help_text='Quantity from this specific batch to use for this bill item')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='The batch from which this item will be dispensed', on_delete=django.db.models.deletion.PROTECT, related_name='bill_assignments', to='pharmacist.medicinebatch')),
                ('bill', models.ForeignKey(help_text='The PharmacyBill this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='pharmacist.pharmacybill')),
                ('medicine_item', models.OneToOneField(help_text='The medicine item in the bill', on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignment', to='pharmacist.pharmacybillmedicineitem')),
            ],
            options={
                'ordering': ['assignment_id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillProcedureItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_description', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_items', to='pharmacist.pharmacybill')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bill_items', to='administration.procedure')),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRY', 'Near Expiry / Expired')], max_length=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pharmacist.medicinebatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INJECTION', 'Injection & Infusion'), ('WOUND_CARE', 'Wound Care & Dressings'), ('RESPIRATORY', 'Respiratory & Oxygen'), ('PPE', 'Personal Protective Equipment'), ('URINARY', 'Urinary & Drainage'), ('COLLECTION', 'Collection & Diagnostic'), ('SURGICAL', 'Surgical & Procedure'), ('HOUSEKEEPING', 'Housekeeping & Safety'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(choices=[('PIECES', 'Pieces'), ('BOXES', 'Boxes'), ('PACKETS', 'Packets'), ('ROLLS', 'Rolls'), ('PAIRS', 'Pairs'), ('LITRES', 'Litres'), ('ML', 'Millilitres'), ('CYLINDERS', 'Cylinders'), ('VIALS', 'Vials'), ('SETS', 'Sets'), ('STRIPS', 'Strips'), ('METRES', 'Metres'), ('KG', 'Kilograms'), ('GRAMS', 'Grams')], default='PIECES', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Spec, size, brand notes', null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='administration.branch')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, help_text='Supplier/invoice batch or lot number (required)', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Current remaining stock')),
                ('original_quantity', models.PositiveIntegerField(help_text='Quantity at time of receipt, never changes')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — to be paid later'), ('PAID', 'Paid in full on receipt')], help_text='How this purchase was/will be settled with the dealer (optional).', max_length=10, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this stock was purchased from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_batches', to='manager.dealer')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_batches_received', to=settings.AUTH_USER_MODEL)),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacist.supplyitem')),
            ],
            options={
                'ordering': ['-purchase_date', '-batch_id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyReturn',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DEFECTIVE', 'Defective'), ('RECALL', 'Recall'), ('EXCESS', 'Excess / Over-ordered'), ('OTHER', 'Other')], default='OTHER', help_text='Why this stock is being returned', max_length=20)),
                ('reason_details', models.CharField(blank=True, help_text='Extra detail about the reason', max_length=300, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Supplier credit note / RMA number', max_length=100, null=True)),
                ('settlement_method', models.CharField(blank=True, choices=[('CREDIT', 'Credit — carried forward against future orders'), ('REFUND', 'Cash refund'), ('EXCHANGE', 'Exchanged for other product(s)')], help_text='How the pharmacist expects this return to be settled by the dealer (optional).', max_length=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text="Refund owed by the supplier — quantity returned × the batch's purchase (unit) cost, NOT the MRP/selling price. Snapshotted at return time.", max_digits=12)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacist.supplybatch')),
                ('dealer', models.ForeignKey(blank=True, help_text='Dealer this return is going back to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_returns', to='manager.dealer')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_returns', to=settings.AUTH_USER_MODEL)),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacist.supplyitem')),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyStockAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('supply_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pharmacist.supplyitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyUsageLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.PositiveIntegerField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('balance_after', models.PositiveIntegerField(blank=True, help_text="Item's total remaining stock (across all batches) immediately after this issue", null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='pharmacist.supplybatch')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='pharmacist.supplyitem')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generalitem',
            index=models.Index(fields=['category'], name='pharmacist__categor_d8fc54_idx'),
        ),
        migrations.AddIndex(
            model_name='generalitem',
            index=models.Index(fields=['is_active'], name='pharmacist__is_acti_f36692_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generalitem',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='generalitembatch',
            index=models.Index(fields=['general_item'], name='pharmacist__general_687f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='generalitembatch',
            index=models.Index(fields=['status'], name='pharmacist__status_c24132_idx'),
        ),
        migrations.AddConstraint(
            model_name='generalitembatch',
            constraint=models.UniqueConstraint(fields=('general_item', 'batch_number'), name='unique_batch_number_per_general_item'),
        ),
        migrations.AddIndex(
            model_name='generalitemreturn',
            index=models.Index(fields=['general_item'], name='pharm_gi_ret_item_idx'),
        ),
        migrations.AddIndex(
            model_name='generalitemreturn',
            index=models.Index(fields=['batch'], name='pharm_gi_ret_batch_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generalitemstockalert',
            unique_together={('batch', 'alert_type')},
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(condition=models.Q(('default_route', ''), _negated=True), name='medicine_default_route_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine'], name='pharmacist__medicin_0b49ea_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['status'], name='pharmacist__status_61309e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['expiry_date'], name='pharmacist__expiry__31a2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['batch_number'], name='pharmacist__batch_n_64b178_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_batch_number_per_medicine'),
        ),
        migrations.AddIndex(
            model_name='medicinereturntoprovider',
            index=models.Index(fields=['status', '-created_at'], name='pharmacist__status_ff57e0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinereturntoprovider',
            index=models.Index(fields=['batch', 'status'], name='pharmacist__batch_i_e05c94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacybill',
            unique_together={('branch', 'bill_number')},
        ),
        migrations.AddIndex(
            model_name='pharmacybillbatchassignment',
            index=models.Index(fields=['bill'], name='pharmacist__bill_id_9e99cb_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacybillbatchassignment',
            index=models.Index(fields=['batch'], name='pharmacist__batch_i_27ba9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacybillbatchassignment',
            unique_together={('bill', 'medicine_item')},
        ),
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together={('batch', 'alert_type')},
        ),
        migrations.AddIndex(
            model_name='supplyitem',
            index=models.Index(fields=['category'], name='pharmacist__categor_7e95bd_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyitem',
            index=models.Index(fields=['is_active'], name='pharmacist__is_acti_420b30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplyitem',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='supplybatch',
            index=models.Index(fields=['supply_item'], name='pharmacist__supply__f5483a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplybatch',
            index=models.Index(fields=['expiry_date'], name='pharmacist__expiry__4c3fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='supplybatch',
            index=models.Index(fields=['batch_number'], name='pharmacist__batch_n_a1f3c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplybatch',
            constraint=models.UniqueConstraint(fields=('supply_item', 'batch_number'), name='unique_batch_number_per_supply_item'),
        ),
        migrations.AddIndex(
            model_name='supplyreturn',
            index=models.Index(fields=['supply_item'], name='pharm_ret_item_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyreturn',
            index=models.Index(fields=['batch'], name='pharm_ret_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyusagelog',
            index=models.Index(fields=['supply_item'], name='pharmacist__supply__bfb684_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyusagelog',
            index=models.Index(fields=['department'], name='pharmacist__departm_d3ffa9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyusagelog',
            index=models.Index(fields=['-used_at'], name='pharmacist__used_at_f48ca5_idx'),
        ),
    ]
