# Generated by Django 5.2.16 on 2026-08-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplybatch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEPLETED', 'Depleted'), ('PENDING_APPROVAL', 'Pending manager approval'), ('REJECTED', 'Rejected — returned to dealer')], default='ACTIVE', max_length=17),
        ),
        migrations.AlterField(
            model_name='generalitembatch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted'), ('PENDING_APPROVAL', 'Pending manager approval'), ('REJECTED', 'Rejected — returned to dealer')], default='ACTIVE', max_length=17),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted'), ('PENDING_APPROVAL', 'Pending manager approval'), ('REJECTED', 'Rejected — returned to dealer')], default='ACTIVE', max_length=17),
        ),
    ]
