# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('LAB_REQUESTED', 'Lab Requested'), ('WAITING_FOR_LAB', 'Waiting for Lab'), ('LAB_COMPLETED', 'Lab Completed'), ('FOLLOWUP_REQUIRED', 'Follow-up Required'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='STARTED', max_length=30)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('vital_signs', models.JSONField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('provisional_diagnosis', models.TextField(blank=True, null=True)),
                ('final_diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
                ('followup_instructions', models.TextField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-consultation_id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationTimeline',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('CREATED', 'Consultation Created'), ('STARTED', 'Consultation Started'), ('LAB_REQUESTED', 'Lab Test Requested'), ('LAB_COMPLETED', 'Lab Results Received'), ('PRESCRIPTION_ISSUED', 'Prescription Issued'), ('COMPLETED', 'Consultation Completed'), ('REOPENED', 'Consultation Reopened'), ('NOTES_UPDATED', 'Notes Updated'), ('STATUS_CHANGED', 'Status Changed'), ('CANCELLED', 'Appointment Cancelled'), ('OTHER', 'Other Event')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, help_text='Deprecated free-text field, kept as a one-release safety net after the migration to `specialty` below. Not written to by new code — do not read this for anything new; use `specialty` instead.', max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile_id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('followup_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('BOOKED', 'Booked'), ('DECLINED', 'Declined'), ('NO_ANSWER', 'No Answer')], default='PENDING', max_length=20)),
                ('reception_notes', models.TextField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['followup_date', 'reminder_id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_type', models.CharField(choices=[('FINAL', 'Final')], default='FINAL', max_length=20)),
                ('prescription_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_sent_to_pharmacy', models.BooleanField(default=False, help_text='True when prescription is sent to pharmacy for dispensing.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-prescription_id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, help_text='Snapshot of medicine name at prescription time.', max_length=300, null=True)),
                ('dose_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Dose per administration (e.g. 1 tablet, 5 ml).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('frequency', models.CharField(choices=[('OD', 'Once Daily'), ('BD', 'Twice Daily'), ('TDS', 'Three Times Daily'), ('QID', 'Four Times Daily'), ('HS', 'At Bedtime'), ('SOS', 'As Needed'), ('STAT', 'Stat (Immediately, One-Time)')], default='OD', help_text='Frequency of administration.', max_length=10)),
                ('meal_timing', models.CharField(blank=True, choices=[('', 'No specific timing'), ('BEFORE_MEALS', 'Before Meals'), ('WITH_MEALS', 'With Meals'), ('AFTER_MEALS', 'After Meals')], default='', help_text='Timing relative to meals.', max_length=12)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Prescription duration in days (max 30 for clinic).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('route', models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('NASAL', 'Nasal'), ('RECTAL', 'Rectal'), ('OTHER', 'Other')], help_text='Administration route. Auto-populated from medicine master.', max_length=10, null=True)),
                ('is_route_overridden', models.BooleanField(default=False, help_text="True if doctor manually overrode the medicine's default route.")),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Total quantity to dispense. Auto-calculated or manual.', null=True)),
                ('calculated_quantity', models.PositiveIntegerField(blank=True, help_text='Auto-calculated quantity (Dose × Freq × Duration).', null=True)),
                ('is_manual_quantity', models.BooleanField(default=False, help_text='True if the doctor manually overrode the auto-calculated quantity.')),
                ('prn_reason', models.CharField(blank=True, choices=[('FEVER', 'Fever'), ('PAIN', 'Pain'), ('ALLERGY', 'Allergic Reaction'), ('COUGH', 'Cough'), ('NAUSEA', 'Nausea/Vomiting'), ('OTHER', 'Other (specify)')], help_text='Required when frequency is SOS/PRN (As Needed).', max_length=20, null=True)),
                ('prn_reason_other', models.CharField(blank=True, help_text="Free-text reason when prn_reason='OTHER'.", max_length=200, null=True)),
                ('max_daily_dose', models.CharField(blank=True, help_text="Optional ceiling for PRN/SOS items, e.g. 'Not more than 4 tablets/day'.", max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
    ]
