# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('doctor', '0001_initial'),
        ('manager', '0001_initial'),
        ('pharmacist', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='reception.consultationbill'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_user',
            field=models.ForeignKey(blank=True, help_text='User account (same for both regular and guest doctors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='guest_doctor',
            field=models.ForeignKey(blank=True, help_text='Visiting/consultant doctor (from GuestDoctorProfile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='administration.guestdoctorprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='reception.patient'),
        ),
        migrations.AddField(
            model_name='consultationtimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_timeline_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationtimeline',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='manager.specialty'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administration.staffprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Regular staff doctor (from DoctorProfile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='reception.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacist.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='doctor.prescription'),
        ),
        migrations.AddIndex(
            model_name='consultationtimeline',
            index=models.Index(fields=['consultation', 'timestamp'], name='doctor_cons_consult_f9e3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationtimeline',
            index=models.Index(fields=['event'], name='doctor_cons_event_064fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'consultation_date'], name='doctor_cons_patient_819143_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='doctor_cons_status_d9cea6_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor_user'], name='doctor_cons_doctor__278e03_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['guest_doctor'], name='doctor_cons_guest_d_a342dd_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['status'], name='doctor_foll_status_a6ffbc_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['followup_date'], name='doctor_foll_followu_2f5e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='doctor_pres_consult_9085b1_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['is_sent_to_pharmacy'], name='doctor_pres_is_sent_a1034f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine'], name='doctor_pres_medicin_564d62_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine_name'], name='doctor_pres_medicin_3288db_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('route', ''), _negated=True), name='prescription_item_route_not_empty'),
        ),
    ]
