# Generated by Django 5.2.16 on 2026-08-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
