# Generated by Django 5.2.16 on 2026-07-31 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short prefix used in staff codes / bill numbers, e.g. TVM, KOL.', max_length=10, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(default='General', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REACTIVATE', 'Reactivate'), ('DEACTIVATE', 'Deactivate')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrd_registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time fee charged when a new MRD/patient record is created.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_home_visit_fee', models.DecimalField(decimal_places=2, default=0, help_text='Manager-set default Home Visit Fee, pre-filled on new Home Visit bills.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_home_visit_travel_charge', models.DecimalField(decimal_places=2, default=0, help_text='Manager-set default Travel Charge, pre-filled on new Home Visit bills.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_settings', to='administration.branch')),
            ],
            options={
                'verbose_name': 'Hospital Settings',
                'verbose_name_plural': 'Hospital Settings',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_group_admin', models.BooleanField(default=False)),
                ('staff_code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('role', models.CharField(choices=[('Receptionist', 'Receptionist'), ('Pharmacist', 'Pharmacist'), ('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Manager', 'Manager')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(default='Not Specified', max_length=255)),
                ('salary_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='Monthly', max_length=10)),
                ('salary', models.PositiveIntegerField(default=10000, help_text='Monthly salary amount. Used as-is when salary_type is Monthly.', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reference daily pay rate. If left as 0, derived from salary for display purposes.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weekly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reference weekly pay rate. If left as 0, derived from daily_rate × 7 for display purposes.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('mandatory_working_days', models.PositiveSmallIntegerField(default=26)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Required for every ordinary staff account. Left null only for the original group-admin superuser account, which is not scoped to any single branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='administration.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('branch', 'phone'), ('branch', 'staff_code')},
            },
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='administration.staffprofile')),
            ],
            options={
                'ordering': ['-profile_id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacistProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to='administration.staffprofile')),
            ],
            options={
                'ordering': ['-profile_id'],
            },
        ),
        migrations.CreateModel(
            name='CommonPharmacistProfile',
            fields=[
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('qualification', models.CharField(default='Not Specified', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-common_pharmacist_id'],
                'unique_together': {('branch', 'common_code')},
            },
        ),
        migrations.CreateModel(
            name='CommonReceptionistProfile',
            fields=[
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('qualification', models.CharField(default='Not Specified', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_receptionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-common_receptionist_id'],
                'unique_together': {('branch', 'common_code')},
            },
        ),
        migrations.CreateModel(
            name='GuestDoctorProfile',
            fields=[
                ('guest_doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for a guest doctor who consults across multiple branches (reference-only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_doctor_profiles', to='administration.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-guest_doctor_id'],
                'unique_together': {('branch', 'guest_code')},
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_pharmacist', models.BooleanField(default=False, help_text="True only for one-off procedures auto-created by the pharmacist's 'instant procedure' billing flow (amount typed per-patient at billing time). These are never shown in the admin-managed procedure catalog/picker, since their charge is not a real standard price - it was whatever that pharmacist typed for that one patient. Kept separate from is_active so admins can still freely activate/deactivate real catalog procedures without accidentally surfacing these one-offs.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Each branch manager prices/activates their own procedure catalog independently.', on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='administration.branch')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
