# Generated by Django 5.2.16 on 2026-08-04 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auditlog_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerBranchAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_access_grants', to='administration.branch')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The group admin who granted this access, for audit purposes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_branch_grants_made', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text="Must be a StaffProfile with role='Manager'. Enforced in clean() too.", limit_choices_to={'role': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='extra_branch_access', to='administration.staffprofile')),
            ],
            options={
                'verbose_name': 'Manager branch access grant',
                'verbose_name_plural': 'Manager branch access grants',
                'ordering': ['branch__name'],
                'unique_together': {('manager', 'branch')},
            },
        ),
    ]
