# Generated by Django 5.2.16 on 2026-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_managerbranchaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP the action was performed from. Resolved at log-creation time from the in-flight request (administration.audit.get_current_ip, backed by authentication.utils.get_client_ip) — never trusted from client-supplied data. Null only for actions with no request in flight at all, e.g. a management command or migration.', null=True),
        ),
    ]
