# Generated by Django 5.2.16 on 2026-08-04 19:47

import django.db.models.deletion
import django.utils.timezone
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_managerbranchaccess'),
        ('manager', '0002_dealer_deals_in_combos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchWebsiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text="Only published branches appear on the public website's Locations page.")),
                ('description', models.TextField(blank=True, default='', help_text='"About this branch" copy shown on the Locations page.')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of short bullet strings, e.g. ["24/7 Emergency", "Free Parking", "200 Beds"].')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('hours_text', models.CharField(blank=True, default='', help_text='Free-text display hours, e.g. "Mon–Sat: 9:00 AM – 6:00 PM". Not used for booking logic -- purely informational copy for this page.', max_length=255)),
                ('map_url', models.URLField(blank=True, default='', help_text='Google Maps (or similar) link used for the page\'s "Get Directions" button.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=manager.models._website_branch_photo_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(help_text='The operational branch this public content describes.', on_delete=django.db.models.deletion.CASCADE, related_name='website_profile', to='administration.branch')),
            ],
            options={
                'verbose_name': 'Branch Website Profile',
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
