# Generated by Django 5.2.16 on 2026-08-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_branchwebsiteprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientquery',
            name='query_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment Query'), ('FEEDBACK', 'Feedback / Complaint')], db_index=True, default='APPOINTMENT', max_length=15),
        ),
    ]
