# Generated by Django 5.2.16 on 2026-08-06 13:21

import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_branchwebsiteprofile_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._blog_cover_image_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='branchwebsiteprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._website_branch_photo_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='doctorwebsiteprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._website_doctor_photo_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Optional preview image, uploaded manually — we don't scrape Facebook for this.", null=True, upload_to=manager.models._facebook_thumbnail_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=manager.models._gallery_image_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Optional preview image, uploaded manually — we don't scrape Instagram for this.", null=True, upload_to=manager.models._instagram_thumbnail_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='mediaevent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._media_event_cover_image_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._specialty_hero_image_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=manager.models._testimonial_photo_path, validators=[manager.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Shown in the detail page hero, beside the 'Book An Appointment' form.", null=True, upload_to=manager.models._procedure_hero_image_path, validators=[manager.models.validate_image_file_size]),
        ),
    ]
